[package]
name = "manhunt-app"
version = "0.1.0"
description = "A mobile app for playing the game \"manhunt\""
authors = ["Ben C <bwc9876@gmail.com>"]
edition = "2021"

[lib]
name = "manhunt_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde", "now"] }
tokio = { version = "1.45", features = ["sync", "macros", "time"] }
rand = { version = "0.9", features = ["thread_rng"] }
tauri-plugin-geolocation = "2.2"
rand_chacha = "0.9.0"
futures = "0.3.31"
